name: on Release - Add Version + Zip Files + Upload

on:
  release:
    types: [created, updated]
  
jobs:
  zip-files:
    name: Zip Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2   
             
      - name: Composer add Version
        uses: php-actions/composer@v6
        with:
          command: config version ${{  github.ref_name }}
          
      - name: Zip Repo
        run: zip -r ${{ github.event.repository.name }}_${{  github.ref_name }}.zip ./ -x *.github/* *.git* DOCKER_ENV docker_tag output.log
            
      - name: Display structure
        run: ls -R
        working-directory: ${{ github.workspace }}
        
      - name: Create temp folder
        run: mkdir temp
        
      - name: Move ${{ github.event.repository.name }}_${{  github.ref_name }}.zip to /temp/
        run: mv ${{ github.event.repository.name }}_${{  github.ref_name }}.zip ./temp/${{ github.event.repository.name }}_${{  github.ref_name }}.zip
        
      - name: Upload files via ftp
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          remote_dir: "${{ secrets.PATH }}"
          delete: "false"
          local_dir: "${{ github.workspace }}/temp"
          
      - name: Call Webhock
        run: curl -X POST -H "Content-Type:application/json" -d '{"${{  github.ref_name }}":"${{ github.event.repository.name }}_${{  github.ref_name }}.zip"}' https://p629619.mittwaldserver.info/api/github/product/register
